version: '3.8'

services:
  anycubic-mqtt-bridge:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - mqtt-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  mqtt-network:
    driver: bridge