services:
  anycubic-mqtt-bridge:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - mqtt-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    entrypoint: ["/bin/sh", "-c", "mkdir -p /run/dbus && dbus-daemon --system && avahi-daemon --no-drop-root --daemonize && python asm.py"]

networks:
  mqtt-network:
    driver: bridge